import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  {
    ignores: [
      '.next/**', 'node_modules/**', 'coverage/**',
      'test-results/**', 'playwright-report/**',
      // Generated by Next; not ours to lint.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Quantities are strings from the database on purpose (NFR-01); allow the
      // explicit any-free style but keep unused vars as errors.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
];

export default config;
